# Generated by Django 4.2.16 on 2026-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamind', '0008_discoveryvisitlog_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedservice',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='canonical_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='favicon',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='published_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='structured_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
