# Generated by Django 4.2.16 on 2026-08-08 07:01

from django.db import migrations, models
import django.db.models.deletion
import megamind.models.connected_service


class Migration(migrations.Migration):

    dependencies = [
        ('megamind', '0009_connectedservice_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('http_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('error_category', models.CharField(choices=[('none', 'None'), ('timeout', 'Timeout'), ('dns_error', 'DNS Error'), ('ssl_error', 'SSL Error'), ('connection_error', 'Connection Error'), ('http_error', 'HTTP Error'), ('robots_blocked', 'Blocked by robots.txt'), ('rate_limited', 'Rate Limited'), ('ssrf_blocked', 'Blocked (unsafe URL)'), ('content_too_large', 'Content Too Large'), ('parse_error', 'Parse Error'), ('unknown', 'Unknown')], default='none', max_length=30)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('bytes_downloaded', models.PositiveIntegerField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('content_changed', models.BooleanField(blank=True, help_text="Whether content_hash differed from the previous attempt's.", null=True)),
                ('used_conditional_get', models.BooleanField(default=False)),
                ('returned_not_modified', models.BooleanField(default=False)),
                ('worker_id', models.CharField(blank=True, help_text='Hostname/PID/task-id of the worker that made this attempt.', max_length=100, null=True)),
                ('proxy_used', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DomainCrawlPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=255, unique=True)),
                ('robots_txt', models.TextField(blank=True, null=True)),
                ('robots_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('robots_txt_ttl_seconds', models.PositiveIntegerField(default=86400)),
                ('disallow_all', models.BooleanField(default=False)),
                ('crawl_delay_seconds', models.FloatField(default=1.0)),
                ('max_concurrent_requests', models.PositiveIntegerField(default=2)),
                ('user_agent_override', models.CharField(blank=True, max_length=255, null=True)),
                ('requests_in_current_window', models.PositiveIntegerField(default=0)),
                ('window_started_at', models.DateTimeField(blank=True, null=True)),
                ('window_seconds', models.PositiveIntegerField(default=60)),
                ('max_requests_per_window', models.PositiveIntegerField(default=30)),
                ('is_blocked', models.BooleanField(default=False, help_text='Manual block, e.g. domain asked to be excluded or is abusive to scrape.')),
                ('blocked_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='alternate_languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='amp_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='apple_touch_icon',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='article_section',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='article_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='atom_feed_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='author_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='availability',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='brand_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='category_breadcrumb',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='charset',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='circuit_breaker_open',
            field=models.BooleanField(default=False, help_text='Trips after too many consecutive failures; stops due_for_crawl() from returning this row until manually reset or circuit_breaker_until passes.'),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='circuit_breaker_threshold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='circuit_breaker_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='consecutive_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='content_language',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='content_sensitivity',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('clean', 'Clean'), ('pii_detected', 'PII Detected')], default='unknown', help_text='Set by a PII-scan step before extracted_text is persisted/exposed downstream.', max_length=20),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='content_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='content_version',
            field=models.PositiveIntegerField(default=0, help_text='Incremented each time content_hash changes from the previous fetch.'),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='crawl_frequency_minutes',
            field=models.PositiveIntegerField(default=1440, help_text='How often this URL should be recrawled, in minutes.'),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='crawl_priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='1 = highest priority, 10 = lowest. Used to order the crawl queue.'),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='crawl_source',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('webhook', 'Webhook Triggered'), ('backfill', 'Backfill')], default='scheduled', max_length=20),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='created_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='dns_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='etag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='extracted_headings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='fetch_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='fetch_error_category',
            field=models.CharField(choices=[('none', 'None'), ('timeout', 'Timeout'), ('dns_error', 'DNS Error'), ('ssl_error', 'SSL Error'), ('connection_error', 'Connection Error'), ('http_error', 'HTTP Error'), ('robots_blocked', 'Blocked by robots.txt'), ('rate_limited', 'Rate Limited'), ('ssrf_blocked', 'Blocked (unsafe URL)'), ('content_too_large', 'Content Too Large'), ('parse_error', 'Parse Error'), ('unknown', 'Unknown')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='http_status_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft-delete flag. Excluded rows are never picked up by due_for_crawl().'),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='is_indexable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='last_modified_header',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='load_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='lock_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='locked_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='manifest_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='max_crawl_depth',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = only this URL. >0 = follow links up to N hops (if a link-following worker is used).'),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='max_retries',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='meta_generator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='modified_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='next_crawl_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='notify_on_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='og_audio',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='og_locale',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='og_video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='organization_id',
            field=models.CharField(blank=True, db_index=True, help_text="Tenant identifier for multi-tenant deployments. Kept as a plain indexed column rather than a FK so this app doesn't hard-depend on an Organization model existing.", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='page_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='page_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='price_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='price_original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='product_condition',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='product_gtin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='product_sku',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='proxy_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='rating_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='rating_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Allows up to 99.99 since some source schemas rate out of 10 or 100, not just 5.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='redirect_chain',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='render_javascript',
            field=models.BooleanField(default=False, help_text='Whether this page requires a headless browser to render before extraction.'),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='respect_robots_txt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='response_headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='robots_meta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='rss_feed_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='same_as_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='screenshot_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='seller_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='ssl_valid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='theme_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='ttfb_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='twitter_card',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='twitter_creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='twitter_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='twitter_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='twitter_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='viewport',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='webhook_secret',
            field=megamind.models.connected_service.EncryptedCharField(blank=True, max_length=739, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='webhook_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='x_robots_tag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='connectedservice',
            name='api_key',
            field=megamind.models.connected_service.EncryptedCharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AlterField(
            model_name='connectedservice',
            name='auth_token',
            field=megamind.models.connected_service.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connectedservice',
            name='fetch_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked (crawl in progress)'), ('success', 'Success'), ('error', 'Error'), ('not_modified', 'Not Modified (conditional GET)')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['user', 'service_type'], name='megamind_co_user_id_32e25b_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['user', 'status'], name='megamind_co_user_id_0a6e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['fetch_status', 'last_fetch_time'], name='megamind_co_fetch_s_de549e_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['status', 'is_connected'], name='megamind_co_status_09ecf4_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['domain'], name='megamind_co_domain_fbeaf5_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['organization_id'], name='megamind_co_organiz_5212c0_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['crawl_priority', 'next_crawl_at'], name='megamind_co_crawl_p_904b27_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['circuit_breaker_open'], name='megamind_co_circuit_2060f4_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['is_active', 'next_crawl_at'], name='megamind_co_is_acti_8a4110_idx'),
        ),
        migrations.AddIndex(
            model_name='connectedservice',
            index=models.Index(fields=['created_at'], name='megamind_co_created_853d32_idx'),
        ),
        migrations.AddConstraint(
            model_name='connectedservice',
            constraint=models.UniqueConstraint(fields=('user', 'service_url'), name='uniq_user_service_url'),
        ),
        migrations.AddIndex(
            model_name='domaincrawlpolicy',
            index=models.Index(fields=['domain'], name='megamind_do_domain_4bdfbe_idx'),
        ),
        migrations.AddField(
            model_name='crawlattempt',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_attempts', to='megamind.connectedservice'),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='domain_policy',
            field=models.ForeignKey(blank=True, help_text='Auto-linked to the DomainCrawlPolicy matching `domain` on save().', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='megamind.domaincrawlpolicy'),
        ),
        migrations.AddIndex(
            model_name='crawlattempt',
            index=models.Index(fields=['service', '-started_at'], name='megamind_cr_service_6ba7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='crawlattempt',
            index=models.Index(fields=['error_category'], name='megamind_cr_error_c_364ad0_idx'),
        ),
    ]
