# Generated by Django 4.2.16 on 2026-08-08 11:51

from django.db import migrations
import megamind.models.connected_service


class Migration(migrations.Migration):

    dependencies = [
        ('megamind', '0014_alter_connectedservice_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedservice',
            name='api_key',
            field=megamind.models.connected_service.EncryptedCharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='connectedservice',
            name='webhook_secret',
            field=megamind.models.connected_service.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
