# Generated by Django 4.2.16 on 2026-08-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamind', '0015_alter_connectedservice_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedservice',
            name='circuit_breaker_open',
            field=models.BooleanField(default=False, help_text="Trips after too many consecutive failures. due_for_crawl()/needs_retry() skip this row until circuit_breaker_until passes or it's manually reset."),
        ),
        migrations.AlterField(
            model_name='connectedservice',
            name='service_type',
            field=models.CharField(choices=[('general', 'General'), ('education', 'Education'), ('product', 'Product'), ('brand', 'Brand'), ('news', 'News'), ('location', 'Location'), ('person', 'Person'), ('business', 'Business'), ('entertainment', 'Entertainment'), ('social', 'Social'), ('government', 'Government')], db_index=True, default='general', max_length=50),
        ),
    ]
