# Generated by Django 4.2.16 on 2026-08-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamind', '0016_alter_connectedservice_circuit_breaker_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectedservice',
            name='respect_robots_txt',
        ),
        migrations.RemoveField(
            model_name='domaincrawlpolicy',
            name='disallow_all',
        ),
        migrations.RemoveField(
            model_name='domaincrawlpolicy',
            name='robots_fetched_at',
        ),
        migrations.RemoveField(
            model_name='domaincrawlpolicy',
            name='robots_txt',
        ),
        migrations.RemoveField(
            model_name='domaincrawlpolicy',
            name='robots_txt_ttl_seconds',
        ),
        migrations.AlterField(
            model_name='connectedservice',
            name='fetch_error_category',
            field=models.CharField(choices=[('none', 'None'), ('timeout', 'Timeout'), ('dns_error', 'DNS Error'), ('ssl_error', 'SSL Error'), ('connection_error', 'Connection Error'), ('http_error', 'HTTP Error'), ('rate_limited', 'Rate Limited'), ('ssrf_blocked', 'Blocked (unsafe URL)'), ('content_too_large', 'Content Too Large'), ('parse_error', 'Parse Error'), ('unknown', 'Unknown')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='crawlattempt',
            name='error_category',
            field=models.CharField(choices=[('none', 'None'), ('timeout', 'Timeout'), ('dns_error', 'DNS Error'), ('ssl_error', 'SSL Error'), ('connection_error', 'Connection Error'), ('http_error', 'HTTP Error'), ('rate_limited', 'Rate Limited'), ('ssrf_blocked', 'Blocked (unsafe URL)'), ('content_too_large', 'Content Too Large'), ('parse_error', 'Parse Error'), ('unknown', 'Unknown')], default='none', max_length=30),
        ),
    ]
