# apps/customer/admin/profile_view_log_admin.py

"""
Django Admin Configuration for ProfileViewLog
-----------------------------------------------
Read-only audit log of who viewed which profile, when, and from what IP.

Fields (confirmed against apps/customer/models/profile_view_log.py):
    - profile_user : FK to User (CASCADE) -- the profile that was viewed
    - viewer       : FK to User (SET_NULL), nullable -- who viewed it.
                      Nulled proactively by account.py's soft_delete()
                      when the viewer's account is GDPR-deleted, since
                      that method no longer performs a real row delete
                      and on_delete=SET_NULL never fires on its own
                      (see account.py changelog fix #5).
    - viewed_at    : DateTimeField, default=timezone.now, indexed
    - ip_address   : GenericIPAddressField, nullable (also nulled by
                      soft_delete())

Note: there's a unique constraint on (profile_user, viewer) for
non-null viewers -- one row per viewer per profile, updated on revisit
rather than duplicated. Anonymous (viewer=None) views are unconstrained.

This is intentionally a read-only, list-only admin: view logs are an
audit trail, not something that should be hand-edited or created from
the admin UI.
"""

from django.contrib import admin

from apps.customer.models.profile_view_log import ProfileViewLog


@admin.register(ProfileViewLog)
class ProfileViewLogAdmin(admin.ModelAdmin):
    """
    Read-only admin for profile view audit logs.
    """

    list_display = (
        'profile_user_display',
        'viewer_display',
        'ip_address',
        'viewed_at',
    )

    list_filter = (
        'viewed_at',
    )

    search_fields = (
        'viewer__email_or_phone',
        'viewer__email',
        'profile_user__email_or_phone',
        'profile_user__email',
        'ip_address',
    )

    ordering = ('-viewed_at',)

    date_hierarchy = 'viewed_at'

    # ================================================================
    # DISPLAY HELPERS
    # ================================================================

    @admin.display(description='Viewer')
    def viewer_display(self, obj):
        """
        Show '(deleted / anonymized)' when viewer is None -- this is the
        expected state after the viewer's account was soft-deleted via
        account.py's soft_delete(), which nulls this FK proactively
        rather than relying on on_delete=SET_NULL (see fix #5 in
        account.py's changelog).
        """
        return obj.viewer if obj.viewer_id else '(deleted / anonymized)'

    @admin.display(description='Profile Viewed', ordering='profile_user')
    def profile_user_display(self, obj):
        return obj.profile_user

    # ================================================================
    # LOCK DOWN AS A READ-ONLY AUDIT LOG
    # ================================================================

    def has_add_permission(self, request):
        """View logs are generated by app logic, never created in admin."""
        return False

    def has_change_permission(self, request, obj=None):
        """Audit trail entries should never be edited after the fact."""
        return False

    def has_delete_permission(self, request, obj=None):
        """
        Superusers only, for legitimate cleanup/retention-policy purges.
        Regular staff cannot delete audit trail entries.
        """
        return request.user.is_superuser

    def get_readonly_fields(self, request, obj=None):
        """Everything is readonly, for the rare case add/change is ever re-enabled."""
        return [f.name for f in self.model._meta.fields]

    def get_queryset(self, request):
        """Avoid N+1 queries on viewer/profile_user in list_display."""
        return super().get_queryset(request).select_related('viewer', 'profile_user')