# Generated by Django 4.2.16 on 2026-02-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, db_index=True, help_text='Stock Keeping Unit', max_length=100, null=True, unique=True, verbose_name='SKU'),
        ),
    ]
