# Generated by Django 4.2.16 on 2026-05-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_title',
            field=models.CharField(blank=True, db_index=True, help_text='Product title', max_length=200, null=True, verbose_name='Product Title'),
        ),
    ]
