# Generated by Django 4.2.16 on 2026-05-18 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0003_product_product_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for external API references', unique=True, verbose_name='UUID')),
                ('sub_category_name', models.CharField(db_index=True, help_text='SubCategory name', max_length=150, verbose_name='SubCategory Name')),
                ('sub_category_slug', models.SlugField(blank=True, help_text='URL-friendly subcategory identifier', max_length=160, null=True, unique=True, verbose_name='SubCategory Slug')),
                ('sub_category_type', models.CharField(choices=[('product', 'Product SubCategory'), ('service', 'Service SubCategory'), ('digital', 'Digital Goods'), ('physical', 'Physical Goods'), ('mixed', 'Mixed')], default='product', help_text='Type of subcategory', max_length=20, verbose_name='SubCategory Type')),
                ('sub_category_description', models.TextField(blank=True, help_text='Detailed subcategory description', max_length=1000, null=True, verbose_name='SubCategory Description')),
                ('sub_category_short_description', models.CharField(blank=True, help_text='Brief subcategory description', max_length=200, null=True, verbose_name='Short Description')),
                ('sub_category_image', models.ImageField(blank=True, help_text='SubCategory banner/cover image', null=True, upload_to='sub_categories/images/%Y/%m/', verbose_name='SubCategory Image')),
                ('sub_category_icon', models.ImageField(blank=True, help_text='SubCategory icon image', null=True, upload_to='sub_categories/icons/%Y/%m/', verbose_name='SubCategory Icon')),
                ('sub_category_thumbnail', models.ImageField(blank=True, help_text='SubCategory thumbnail image', null=True, upload_to='sub_categories/thumbnails/%Y/%m/', verbose_name='SubCategory Thumbnail')),
                ('icon_class', models.CharField(blank=True, help_text="CSS icon class (e.g. 'fa fa-laptop')", max_length=50, null=True, verbose_name='Icon Class')),
                ('color_code', models.CharField(blank=True, help_text="Hex color code for subcategory theme (e.g. '#FF5733')", max_length=7, null=True, verbose_name='Color Code')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='SubCategory is active and visible', verbose_name='Active')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='SubCategory is featured on its parent category page', verbose_name='Featured')),
                ('is_trending', models.BooleanField(default=False, help_text='SubCategory is currently trending', verbose_name='Trending')),
                ('is_visible_in_menu', models.BooleanField(default=True, help_text='Show subcategory in navigation menu', verbose_name='Visible in Menu')),
                ('is_visible_on_homepage', models.BooleanField(default=False, help_text='Show subcategory on homepage', verbose_name='Visible on Homepage')),
                ('display_style', models.CharField(choices=[('grid', 'Grid View'), ('list', 'List View'), ('carousel', 'Carousel View'), ('featured', 'Featured View')], default='grid', help_text='How to display products in this subcategory', max_length=20, verbose_name='Display Style')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order for display (lower number = higher priority)', verbose_name='Display Order')),
                ('products_per_page', models.PositiveIntegerField(default=24, help_text='Number of products to show per page', verbose_name='Products Per Page')),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title (60 chars max)', max_length=60, null=True, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description (160 chars max)', max_length=160, null=True, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=255, null=True, verbose_name='Meta Keywords')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL for SEO', null=True, verbose_name='Canonical URL')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Total subcategory page views', verbose_name='View Count')),
                ('product_count', models.PositiveIntegerField(default=0, help_text='Cached product count', verbose_name='Product Count')),
                ('popularity_score', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated popularity score', max_digits=10, verbose_name='Popularity Score')),
                ('last_viewed_at', models.DateTimeField(blank=True, help_text='Last time subcategory page was viewed', null=True, verbose_name='Last Viewed At')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission percentage (0-100). Overrides parent category rate when set above 0.', max_digits=5, verbose_name='Commission Rate')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum allowed price for products in this subcategory', max_digits=10, null=True, verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed price for products in this subcategory', max_digits=10, null=True, verbose_name='Maximum Price')),
                ('sub_category_created_at', models.DateTimeField(auto_now_add=True, help_text='When subcategory was created', verbose_name='Created At')),
                ('sub_category_updated_at', models.DateTimeField(auto_now=True, help_text='Last time subcategory was updated', verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp', null=True, verbose_name='Deleted At')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for deletion', max_length=500, null=True, verbose_name='Deletion Reason')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional subcategory metadata in JSON format', verbose_name='Metadata')),
                ('category', models.ForeignKey(help_text='Parent category this subcategory belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='ponno.category')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_sub_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SubCategory',
                'verbose_name_plural': 'SubCategories',
                'db_table': 'sub_categories',
                'ordering': ['display_order', 'sub_category_name'],
                'indexes': [models.Index(fields=['uuid'], name='sub_categor_uuid_375c31_idx'), models.Index(fields=['sub_category_slug'], name='sub_categor_sub_cat_547bf8_idx'), models.Index(fields=['sub_category_name'], name='sub_categor_sub_cat_731adf_idx'), models.Index(fields=['category'], name='sub_categor_categor_e70bb6_idx'), models.Index(fields=['is_active', 'deleted_at'], name='sub_categor_is_acti_9fcfde_idx'), models.Index(fields=['is_featured'], name='sub_categor_is_feat_bbd25f_idx'), models.Index(fields=['display_order'], name='sub_categor_display_80f1d9_idx'), models.Index(fields=['popularity_score'], name='sub_categor_popular_3cf01a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='subcategory',
            constraint=models.CheckConstraint(check=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), name='sub_category_commission_rate_range'),
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'sub_category_name')},
        ),
    ]
