# Generated by Django 4.2.16 on 2026-05-18 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0004_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Public-facing order identifier', unique=True)),
                ('order_number', models.CharField(db_index=True, help_text='Human-readable order number, e.g. ORD-20240516-0001', max_length=30, unique=True, verbose_name='Order Number')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='Order Status')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partial'), ('refunded', 'Refunded')], db_index=True, default='unpaid', max_length=20, verbose_name='Payment Status')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Discount Total')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Shipping Total')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Grand Total')),
                ('currency', models.CharField(default='BDT', max_length=3, verbose_name='Currency')),
                ('shipping_name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('shipping_phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('shipping_address', models.TextField(blank=True, verbose_name='Address')),
                ('shipping_city', models.CharField(blank=True, max_length=100, verbose_name='City')),
                ('shipping_country', models.CharField(blank=True, max_length=2, verbose_name='Country')),
                ('placed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Placed At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('user', models.ForeignKey(help_text='Customer who placed the order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='sub_category',
            field=models.ForeignKey(blank=True, help_text='Product sub-category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='ponno.subcategory'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('product_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('product_image', models.URLField(blank=True, max_length=500, verbose_name='Image URL')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Price')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount %')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Line Total')),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ponno.order')),
                ('product', models.ForeignKey(help_text='Ordered product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='ponno.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the product was added to the wishlist', verbose_name='Added At')),
                ('note', models.CharField(blank=True, help_text='Optional personal note', max_length=255, null=True, verbose_name='Note')),
                ('product', models.ForeignKey(help_text='Wishlisted product', on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='ponno.product')),
                ('user', models.ForeignKey(help_text='User who wishlisted the product', on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist Items',
                'db_table': 'user_wishlist',
                'ordering': ['-added_at'],
                'indexes': [models.Index(fields=['user', 'added_at'], name='user_wishli_user_id_890709_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, help_text='The search term entered by the user', max_length=200, verbose_name='Search Query')),
                ('result_count', models.PositiveIntegerField(default=0, help_text='Number of products returned for this query', verbose_name='Result Count')),
                ('searched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Searched At')),
                ('search_count', models.PositiveIntegerField(default=1, help_text='How many times this query was repeated', verbose_name='Search Count')),
                ('user', models.ForeignKey(help_text='User who performed the search', on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Search History',
                'verbose_name_plural': 'Search Histories',
                'db_table': 'user_search_history',
                'ordering': ['-searched_at'],
                'indexes': [models.Index(fields=['user', 'searched_at'], name='user_search_user_id_c714a9_idx'), models.Index(fields=['user', 'query'], name='user_search_user_id_f15964_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Last time the user viewed this product', verbose_name='Viewed At')),
                ('view_count', models.PositiveIntegerField(default=1, help_text='How many times this user viewed this product', verbose_name='View Count')),
                ('product', models.ForeignKey(help_text='Product that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='user_views', to='ponno.product')),
                ('user', models.ForeignKey(help_text='User who viewed the product', on_delete=django.db.models.deletion.CASCADE, related_name='product_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product View',
                'verbose_name_plural': 'Product Views',
                'db_table': 'user_product_views',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['user', 'viewed_at'], name='user_produc_user_id_24fcfd_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_user_id_17dbdf_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['placed_at'], name='orders_placed__34697f_idx'),
        ),
    ]
