# Generated by Django 4.2.16 on 2026-05-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0005_order_product_sub_category_orderitem_wishlist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='features',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_info',
            field=models.JSONField(blank=True, default=dict, help_text='Delivery details (JSON)', null=True, verbose_name='Delivery Information'),
        ),
        migrations.AddField(
            model_name='product',
            name='warrenty_info',
            field=models.TextField(blank=True, help_text='Warranty information', max_length=2000, null=True, verbose_name='Warranty'),
        ),
    ]
