# Generated by Django 4.2.16 on 2026-05-31 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0006_remove_product_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand associated with this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='ponno.brand'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='brand',
            field=models.ForeignKey(blank=True, help_text='Brand Category associated with this subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='ponno.brand'),
        ),
    ]
