# Generated by Django 4.2.16 on 2026-06-08 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0007_category_brand_subcategory_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for external API references', unique=True, verbose_name='UUID')),
                ('session_key', models.CharField(blank=True, db_index=True, help_text='Django session key — used to correlate anonymous views', max_length=40, null=True, verbose_name='Session Key')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of the most recent view', verbose_name='Viewed At')),
                ('view_count', models.PositiveIntegerField(default=1, help_text='How many times this viewer has viewed this product', verbose_name='View Count')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Visitor IP address at time of view', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser / client user-agent string', null=True, verbose_name='User Agent')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot / Crawler'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='Type of device used to view the product', max_length=10, verbose_name='Device Type')),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('search', 'Search Engine'), ('social', 'Social Media'), ('email', 'Email'), ('referral', 'Referral'), ('ad', 'Advertisement'), ('internal', 'Internal Navigation'), ('unknown', 'Unknown')], db_index=True, default='unknown', help_text='How the visitor arrived at the product page', max_length=20, verbose_name='Traffic Source')),
                ('referrer_url', models.URLField(blank=True, help_text='Full URL of the page that linked to this product', max_length=500, null=True, verbose_name='Referrer URL')),
                ('utm_source', models.CharField(blank=True, help_text="UTM source parameter (e.g. 'google', 'newsletter')", max_length=100, null=True, verbose_name='UTM Source')),
                ('utm_medium', models.CharField(blank=True, help_text="UTM medium parameter (e.g. 'cpc', 'email')", max_length=100, null=True, verbose_name='UTM Medium')),
                ('utm_campaign', models.CharField(blank=True, help_text='UTM campaign parameter', max_length=100, null=True, verbose_name='UTM Campaign')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp', null=True, verbose_name='Deleted At')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional view log metadata in JSON format', verbose_name='Metadata')),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this log entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_product_view_logs', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product that was viewed', on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='ponno.product')),
                ('viewer', models.ForeignKey(blank=True, help_text='Authenticated user who viewed the product (null = anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_view_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product View Log',
                'verbose_name_plural': 'Product View Logs',
                'db_table': 'product_view_logs',
                'ordering': ['-viewed_at'],
                'indexes': [models.Index(fields=['uuid'], name='product_vie_uuid_46cc8b_idx'), models.Index(fields=['product', 'viewed_at'], name='product_vie_product_d4df3e_idx'), models.Index(fields=['viewer', 'viewed_at'], name='product_vie_viewer__1ccd5f_idx'), models.Index(fields=['session_key'], name='product_vie_session_4e28cb_idx'), models.Index(fields=['ip_address'], name='product_vie_ip_addr_9ce020_idx'), models.Index(fields=['device_type'], name='product_vie_device__8f03bb_idx'), models.Index(fields=['source'], name='product_vie_source_f2bb3a_idx'), models.Index(fields=['viewed_at'], name='product_vie_viewed__4ff5d5_idx'), models.Index(fields=['deleted_at'], name='product_vie_deleted_bedeca_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='productviewlog',
            constraint=models.UniqueConstraint(condition=models.Q(('viewer__isnull', False)), fields=('product', 'viewer'), name='unique_product_view_per_viewer'),
        ),
    ]
