# Generated by Django 4.2.16 on 2026-06-13 06:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0008_productviewlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='1–5 star rating', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('rated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Rated At')),
                ('product', models.ForeignKey(help_text='Rated product', on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='ponno.product')),
                ('user', models.ForeignKey(help_text='User who rated the product', on_delete=django.db.models.deletion.CASCADE, related_name='product_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Rating',
                'verbose_name_plural': 'Product Ratings',
                'db_table': 'product_ratings',
                'ordering': ['-rated_at'],
                'indexes': [models.Index(fields=['product', 'rating'], name='product_rat_product_372640_idx'), models.Index(fields=['user', 'rated_at'], name='product_rat_user_id_7ca2bb_idx')],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
