# Generated by Django 4.2.16 on 2026-06-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0009_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='share_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Times shared', null=True, verbose_name='Shares'),
        ),
    ]
