# Generated by Django 4.2.16 on 2026-06-22 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0010_product_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brander', to=settings.AUTH_USER_MODEL),
        ),
    ]
