# Generated by Django 4.2.16 on 2026-06-22 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0011_category_created_by_alter_brand_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='managed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this Category', related_name='managed_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
