# Generated by Django 4.2.16 on 2026-07-09 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0012_category_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this subcategory', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='managed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this SubCategory', null=True, related_name='managed_subcategories', to=settings.AUTH_USER_MODEL),
        ),
    ]
