# Generated by Django 4.2.16 on 2026-07-13 22:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0013_subcategory_created_by_subcategory_managed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='buying_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Buying Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Discount percentage', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Discount %'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Selling Price'),
        ),
    ]
