# Generated by Django 4.2.16 on 2026-07-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0014_alter_product_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_brand_price_visible',
            field=models.BooleanField(blank=True, default=True, help_text="Display manufacturer's price (MRP) to customers", null=True, verbose_name='Show Brand Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_buying_price_visible',
            field=models.BooleanField(blank=True, default=False, help_text='Display cost price (usually internal-only, keep hidden from customers)', null=True, verbose_name='Show Buying Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_selling_price_visible',
            field=models.BooleanField(blank=True, default=True, help_text='Display selling price to customers', null=True, verbose_name='Show Selling Price'),
        ),
    ]
