# Generated by Django 4.2.16 on 2026-07-24 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0015_product_is_brand_price_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_at_visit', models.CharField(blank=True, db_index=True, editable=False, help_text='Snapshot of user.role at visit time. Null for anonymous.', max_length=32, null=True)),
                ('is_authenticated', models.BooleanField(db_index=True, default=False, editable=False)),
                ('session_key', models.CharField(blank=True, default='', editable=False, max_length=40)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
                ('user_agent', models.CharField(blank=True, default='', editable=False, max_length=512)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot / Crawler'), ('unknown', 'Unknown')], db_index=True, default='unknown', editable=False, max_length=10)),
                ('referrer', models.CharField(blank=True, default='', editable=False, max_length=1000)),
                ('query_string', models.CharField(blank=True, default='', editable=False, max_length=1000)),
                ('search_query', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('filter_slug', models.CharField(blank=True, default='', editable=False, max_length=255)),
                ('sort_by', models.CharField(blank=True, default='', editable=False, max_length=50)),
                ('page_number', models.PositiveIntegerField(default=1, editable=False)),
                ('visited_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, editable=False, help_text='Null for anonymous visitors.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovery_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discovery visit log',
                'verbose_name_plural': 'Discovery visit logs',
                'db_table': 'ponno_discovery_visit_log',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['user', 'visited_at'], name='ponno_disco_user_id_2059cd_idx'), models.Index(fields=['role_at_visit', 'visited_at'], name='ponno_disco_role_at_0281f3_idx'), models.Index(fields=['ip_address', 'visited_at'], name='ponno_disco_ip_addr_3caa66_idx')],
            },
        ),
    ]
