# Generated by Django 4.2.16 on 2026-07-25 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0016_discoveryvisitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='managed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this SubCategory', related_name='managed_subcategories', to=settings.AUTH_USER_MODEL),
        ),
    ]
