# Generated by Django 4.2.16 on 2026-05-27 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_views_received', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile_view_log',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='profileviewlog',
            constraint=models.UniqueConstraint(condition=models.Q(('viewer__isnull', False)), fields=('profile_user', 'viewer'), name='unique_profile_view_per_viewer'),
        ),
    ]
