# Generated by Django 4.2.16 on 2026-07-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profileviewlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='UTC', help_text="User's preferred IANA timezone, e.g. 'Asia/Dhaka'", max_length=64, verbose_name='Timezone'),
        ),
    ]
