# Generated by Django 4.2.16 on 2026-08-03 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0017_alter_subcategory_managed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cached average customer rating (0.00 - 5.00)', max_digits=3, verbose_name='Average Rating'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_intro_video_url',
            field=models.URLField(blank=True, help_text='Link to brand introduction video (YouTube/Vimeo, etc.)', max_length=300, null=True, verbose_name='Intro Video URL'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_primary_color',
            field=models.CharField(blank=True, help_text='Hex color code, e.g. #FF5733', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g. #FF5733', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Primary Color'),
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_secondary_color',
            field=models.CharField(blank=True, help_text='Hex color code, e.g. #1A1A1A', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g. #FF5733', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Secondary Color'),
        ),
        migrations.AddField(
            model_name='brand',
            name='business_registration_number',
            field=models.CharField(blank=True, help_text='Official business/company registration number', max_length=100, null=True, verbose_name='Business Registration Number'),
        ),
        migrations.AddField(
            model_name='brand',
            name='category_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of active categories owned by this brand', verbose_name='Category Count'),
        ),
        migrations.AddField(
            model_name='brand',
            name='parent_brand',
            field=models.ForeignKey(blank=True, help_text='Parent brand, if this is a sub-brand', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_brands', to='ponno.brand'),
        ),
        migrations.AddField(
            model_name='brand',
            name='review_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached total number of customer reviews', verbose_name='Review Count'),
        ),
        migrations.AddField(
            model_name='brand',
            name='subcategory_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of active subcategories owned by this brand', verbose_name='SubCategory Count'),
        ),
        migrations.AddField(
            model_name='brand',
            name='tax_identification_number',
            field=models.CharField(blank=True, help_text='TIN / BIN or equivalent tax ID', max_length=100, null=True, verbose_name='Tax Identification Number'),
        ),
        migrations.AddField(
            model_name='brand',
            name='trade_license_number',
            field=models.CharField(blank=True, help_text='Trade license number, if applicable', max_length=100, null=True, verbose_name='Trade License Number'),
        ),
        migrations.AddField(
            model_name='brand',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp contact number, including country code', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +8801XXXXXXXXX', regex='^\\+?[1-9]\\d{6,14}$')], verbose_name='WhatsApp Number'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_phone',
            field=models.CharField(blank=True, help_text='Brand contact phone', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +8801XXXXXXXXX', regex='^\\+?[1-9]\\d{6,14}$')], verbose_name='Brand Phone'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='country_of_origin',
            field=models.CharField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Albania', 'Albania'), ('Algeria', 'Algeria'), ('Andorra', 'Andorra'), ('Angola', 'Angola'), ('Antigua and Barbuda', 'Antigua and Barbuda'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australia', 'Australia'), ('Austria', 'Austria'), ('Azerbaijan', 'Azerbaijan'), ('Bahamas', 'Bahamas'), ('Bahrain', 'Bahrain'), ('Bangladesh', 'Bangladesh'), ('Barbados', 'Barbados'), ('Belarus', 'Belarus'), ('Belgium', 'Belgium'), ('Belize', 'Belize'), ('Benin', 'Benin'), ('Bhutan', 'Bhutan'), ('Bolivia', 'Bolivia'), ('Bosnia and Herzegovina', 'Bosnia and Herzegovina'), ('Botswana', 'Botswana'), ('Brazil', 'Brazil'), ('Brunei', 'Brunei'), ('Bulgaria', 'Bulgaria'), ('Burkina Faso', 'Burkina Faso'), ('Burundi', 'Burundi'), ('Cabo Verde', 'Cabo Verde'), ('Cambodia', 'Cambodia'), ('Cameroon', 'Cameroon'), ('Canada', 'Canada'), ('Central African Republic', 'Central African Republic'), ('Chad', 'Chad'), ('Chile', 'Chile'), ('China', 'China'), ('Colombia', 'Colombia'), ('Comoros', 'Comoros'), ('Congo', 'Congo'), ('Costa Rica', 'Costa Rica'), ('Croatia', 'Croatia'), ('Cuba', 'Cuba'), ('Cyprus', 'Cyprus'), ('Czechia', 'Czechia'), ('Denmark', 'Denmark'), ('Djibouti', 'Djibouti'), ('Dominica', 'Dominica'), ('Dominican Republic', 'Dominican Republic'), ('DR Congo', 'DR Congo'), ('Ecuador', 'Ecuador'), ('Egypt', 'Egypt'), ('El Salvador', 'El Salvador'), ('Equatorial Guinea', 'Equatorial Guinea'), ('Eritrea', 'Eritrea'), ('Estonia', 'Estonia'), ('Eswatini', 'Eswatini'), ('Ethiopia', 'Ethiopia'), ('Fiji', 'Fiji'), ('Finland', 'Finland'), ('France', 'France'), ('Gabon', 'Gabon'), ('Gambia', 'Gambia'), ('Georgia', 'Georgia'), ('Germany', 'Germany'), ('Ghana', 'Ghana'), ('Greece', 'Greece'), ('Grenada', 'Grenada'), ('Guatemala', 'Guatemala'), ('Guinea', 'Guinea'), ('Guinea-Bissau', 'Guinea-Bissau'), ('Guyana', 'Guyana'), ('Haiti', 'Haiti'), ('Honduras', 'Honduras'), ('Hungary', 'Hungary'), ('Iceland', 'Iceland'), ('India', 'India'), ('Indonesia', 'Indonesia'), ('Iran', 'Iran'), ('Iraq', 'Iraq'), ('Ireland', 'Ireland'), ('Israel', 'Israel'), ('Italy', 'Italy'), ('Jamaica', 'Jamaica'), ('Japan', 'Japan'), ('Jordan', 'Jordan'), ('Kazakhstan', 'Kazakhstan'), ('Kenya', 'Kenya'), ('Kiribati', 'Kiribati'), ('Kuwait', 'Kuwait'), ('Kyrgyzstan', 'Kyrgyzstan'), ('Laos', 'Laos'), ('Latvia', 'Latvia'), ('Lebanon', 'Lebanon'), ('Lesotho', 'Lesotho'), ('Liberia', 'Liberia'), ('Libya', 'Libya'), ('Liechtenstein', 'Liechtenstein'), ('Lithuania', 'Lithuania'), ('Luxembourg', 'Luxembourg'), ('Madagascar', 'Madagascar'), ('Malawi', 'Malawi'), ('Malaysia', 'Malaysia'), ('Maldives', 'Maldives'), ('Mali', 'Mali'), ('Malta', 'Malta'), ('Marshall Islands', 'Marshall Islands'), ('Mauritania', 'Mauritania'), ('Mauritius', 'Mauritius'), ('Mexico', 'Mexico'), ('Micronesia', 'Micronesia'), ('Moldova', 'Moldova'), ('Monaco', 'Monaco'), ('Mongolia', 'Mongolia'), ('Montenegro', 'Montenegro'), ('Morocco', 'Morocco'), ('Mozambique', 'Mozambique'), ('Myanmar', 'Myanmar'), ('Namibia', 'Namibia'), ('Nauru', 'Nauru'), ('Nepal', 'Nepal'), ('Netherlands', 'Netherlands'), ('New Zealand', 'New Zealand'), ('Nicaragua', 'Nicaragua'), ('Niger', 'Niger'), ('Nigeria', 'Nigeria'), ('North Korea', 'North Korea'), ('North Macedonia', 'North Macedonia'), ('Norway', 'Norway'), ('Oman', 'Oman'), ('Pakistan', 'Pakistan'), ('Palau', 'Palau'), ('Palestine', 'Palestine'), ('Panama', 'Panama'), ('Papua New Guinea', 'Papua New Guinea'), ('Paraguay', 'Paraguay'), ('Peru', 'Peru'), ('Philippines', 'Philippines'), ('Poland', 'Poland'), ('Portugal', 'Portugal'), ('Qatar', 'Qatar'), ('Romania', 'Romania'), ('Russia', 'Russia'), ('Rwanda', 'Rwanda'), ('Saint Kitts and Nevis', 'Saint Kitts and Nevis'), ('Saint Lucia', 'Saint Lucia'), ('Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'), ('Samoa', 'Samoa'), ('San Marino', 'San Marino'), ('Sao Tome and Principe', 'Sao Tome and Principe'), ('Saudi Arabia', 'Saudi Arabia'), ('Senegal', 'Senegal'), ('Serbia', 'Serbia'), ('Seychelles', 'Seychelles'), ('Sierra Leone', 'Sierra Leone'), ('Singapore', 'Singapore'), ('Slovakia', 'Slovakia'), ('Slovenia', 'Slovenia'), ('Solomon Islands', 'Solomon Islands'), ('Somalia', 'Somalia'), ('South Africa', 'South Africa'), ('South Korea', 'South Korea'), ('South Sudan', 'South Sudan'), ('Spain', 'Spain'), ('Sri Lanka', 'Sri Lanka'), ('Sudan', 'Sudan'), ('Suriname', 'Suriname'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Syria', 'Syria'), ('Taiwan', 'Taiwan'), ('Tajikistan', 'Tajikistan'), ('Tanzania', 'Tanzania'), ('Thailand', 'Thailand'), ('Timor-Leste', 'Timor-Leste'), ('Togo', 'Togo'), ('Tonga', 'Tonga'), ('Trinidad and Tobago', 'Trinidad and Tobago'), ('Tunisia', 'Tunisia'), ('Turkey', 'Turkey'), ('Turkmenistan', 'Turkmenistan'), ('Tuvalu', 'Tuvalu'), ('Uganda', 'Uganda'), ('Ukraine', 'Ukraine'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Uruguay', 'Uruguay'), ('Uzbekistan', 'Uzbekistan'), ('Vanuatu', 'Vanuatu'), ('Vatican City', 'Vatican City'), ('Venezuela', 'Venezuela'), ('Vietnam', 'Vietnam'), ('Yemen', 'Yemen'), ('Zambia', 'Zambia'), ('Zimbabwe', 'Zimbabwe')], db_index=True, help_text='Country of origin', max_length=100, null=True, verbose_name='Country of Origin'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='product_count',
            field=models.PositiveIntegerField(default=0, help_text='Cached count of active products under this brand', verbose_name='Product Count'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='support_phone',
            field=models.CharField(blank=True, help_text='Customer support phone', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number, e.g. +8801XXXXXXXXX', regex='^\\+?[1-9]\\d{6,14}$')], verbose_name='Support Phone'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['average_rating'], name='brands_average_2ceafc_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['category_count'], name='brands_categor_b8e54f_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['subcategory_count'], name='brands_subcate_2c8208_idx'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.CheckConstraint(check=models.Q(('average_rating__gte', 0), ('average_rating__lte', 5)), name='average_rating_range'),
        ),
    ]
