# Generated by Django 4.2.16 on 2026-08-06 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0018_brand_average_rating_brand_brand_intro_video_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('product', 'Product Category'), ('service', 'Service Category'), ('digital', 'Digital Goods'), ('physical', 'Physical Goods'), ('mixed', 'Mixed')], db_index=True, default='product', help_text='Type of category', max_length=20, verbose_name='Category Type'),
        ),
        migrations.AlterField(
            model_name='category',
            name='color_code',
            field=models.CharField(blank=True, help_text='Hex color code for category theme, e.g. #FF5733', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code, e.g. #FF5733', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Color Code'),
        ),
        migrations.AlterField(
            model_name='category',
            name='managed_by',
            field=models.ManyToManyField(blank=True, help_text='Users who can manage this category', related_name='managed_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['brand'], name='categories_brand_i_7606f3_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_type'], name='categories_categor_304e6b_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['product_count'], name='categories_product_6b7c09_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(check=models.Q(('min_price__isnull', True), ('max_price__isnull', True), ('min_price__lte', models.F('max_price')), _connector='OR'), name='category_min_price_lte_max_price'),
        ),
    ]
