# Generated by Django 4.2.16 on 2026-08-10 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megamind', '0015_alter_connectedservice_api_key_and_more'),
        ('ponno', '0019_alter_category_category_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='connected_service',
            field=models.OneToOneField(blank=True, help_text="The ConnectedService this product was auto-created/synced from, if any. SET_NULL (not CASCADE) so soft-deleting the service doesn't take the product down with it — the product keeps whatever data it last synced.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='synced_product', to='megamind.connectedservice'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['connected_service'], name='products_connect_5ed1f3_idx'),
        ),
    ]
