# Generated by Django 4.2.16 on 2026-08-14 06:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0020_product_connected_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Campaign UUID')),
                ('name', models.CharField(help_text="Internal / customer-facing name, e.g. 'Eid Flash Sale'", max_length=150, verbose_name='Campaign Name')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly identifier, auto-generated from name', max_length=170, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='campaigns/%Y/%m/', verbose_name='Banner Image')),
                ('terms_conditions', models.TextField(blank=True, null=True, verbose_name='Terms & Conditions')),
                ('campaign_type', models.CharField(choices=[('percentage', 'Percentage Off'), ('fixed_amount', 'Fixed Amount Off')], default='percentage', max_length=20, verbose_name='Campaign Type')),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) when type=percentage, or a currency amount when type=fixed_amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Discount Value')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Optional cap on the discount actually applied. Mainly useful for percentage campaigns, e.g. '30% off, up to ৳500'. Ignored if blank.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Max Discount Amount')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='If set, the campaign only applies when the order/cart subtotal is at least this amount. Checked by the pricing service at cart/checkout resolution, not at the per-product level.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Minimum Order Amount')),
                ('applies_to', models.CharField(choices=[('all_products', 'All Products'), ('specific_products', 'Specific Products'), ('specific_categories', 'Specific Categories'), ('specific_brands', 'Specific Brands')], default='all_products', max_length=25, verbose_name='Applies To')),
                ('start_at', models.DateTimeField(db_index=True, help_text='When the campaign becomes active', verbose_name='Start At')),
                ('end_at', models.DateTimeField(blank=True, db_index=True, help_text='When the campaign stops being active. Blank = no end date.', null=True, verbose_name='End At')),
                ('usage_limit_total', models.PositiveIntegerField(default=0, help_text='Max number of times this campaign can be redeemed across all users. 0 = unlimited.', verbose_name='Total Usage Limit')),
                ('usage_limit_per_user', models.PositiveIntegerField(default=0, help_text='Max number of times a single user can redeem this campaign. 0 = unlimited.', verbose_name='Per-User Usage Limit')),
                ('times_used', models.PositiveIntegerField(default=0, editable=False, help_text='Running redemption count, incremented atomically by CampaignPricingService.redeem().', verbose_name='Times Used')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='When multiple campaigns are applicable to the same product and are NOT stackable with each other, the highest-priority one wins. Ties broken by largest discount_value.', verbose_name='Priority')),
                ('is_stackable', models.BooleanField(default=False, help_text='If True, this campaign can be combined with other stackable campaigns applicable to the same product. If False (default), it is applied exclusively — the single best-priority campaign wins and all others (stackable or not) are ignored for that product. See CampaignPricingService for the exact resolution algorithm.', verbose_name='Stackable')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, help_text='Manual on/off switch, independent of the start_at/end_at window. A disabled campaign never appears in .active(), even mid-window.', verbose_name='Enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('brands', models.ManyToManyField(blank=True, help_text='Used when applies_to=specific_brands', related_name='campaigns', to='ponno.brand')),
                ('categories', models.ManyToManyField(blank=True, help_text='Used when applies_to=specific_categories', related_name='campaigns', to='ponno.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, help_text='Used when applies_to=specific_products', related_name='campaigns', to='ponno.product')),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'db_table': 'campaigns',
                'ordering': ['-priority', '-start_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('redeemed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Redeemed At')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='ponno.campaign')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_redemptions', to='ponno.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_redemptions', to='ponno.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_redemptions', to='ponno.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign Redemption',
                'verbose_name_plural': 'Campaign Redemptions',
                'db_table': 'campaign_redemptions',
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['campaign', 'user'], name='campaign_re_campaig_912a83_idx'), models.Index(fields=['campaign', 'redeemed_at'], name='campaign_re_campaig_a307f1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['campaign_id'], name='campaigns_campaig_c7c801_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['slug'], name='campaigns_slug_6856b4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_enabled', 'start_at', 'end_at'], name='campaigns_is_enab_b96d11_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['applies_to'], name='campaigns_applies_43e5dd_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['priority'], name='campaigns_priorit_6a6e37_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR'), name='campaign_end_after_start'),
        ),
    ]
