# Generated by Django 4.2.16 on 2026-08-14 19:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ponno', '0021_campaign_campaignredemption_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_campaig_c7c801_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_slug_6856b4_idx',
        ),
        migrations.RemoveIndex(
            model_name='campaign',
            name='campaigns_is_enab_b96d11_idx',
        ),
        migrations.AddField(
            model_name='campaign',
            name='approval_status',
            field=models.CharField(choices=[('not_required', 'Approval Not Required'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', help_text='Independent of is_enabled: a campaign only counts as effectively live once approval_status is APPROVED or NOT_REQUIRED *and* is_enabled=True. See Campaign.active().', max_length=15, verbose_name='Approval Status'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='approved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='archived_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Archived At'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_archived', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap on total discount amount (in `currency`) this campaign may give away across all redemptions combined. Blank = no budget cap. Enforced alongside, not instead of, usage_limit_total.', max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Budget Limit'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='budget_spent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Running total of discount amount given away. Only ever modified by Campaign.register_redemption().', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Budget Spent'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_code',
            field=models.CharField(blank=True, help_text='Optional external reference code (e.g. for POS lookups or coupon-style entry), distinct from the customer-facing URL slug. Leave blank if this campaign is only ever resolved automatically by scope/schedule.', max_length=40, null=True, unique=True, verbose_name='Campaign Code'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='channel',
            field=models.CharField(choices=[('all', 'All Channels'), ('web', 'Web Storefront'), ('app', 'Mobile App'), ('pos', 'Point of Sale')], default='all', help_text='Which storefront surface this campaign is allowed to be applied on.', max_length=10, verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='currency',
            field=models.CharField(default='BDT', help_text='ISO 4217 currency code that discount_value / max_discount_amount / min_order_amount / budget_limit are denominated in when campaign_type=fixed_amount. Purely informational for percentage campaigns.', max_length=3, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='first_activated_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Set automatically the first time is_enabled transitions to True. Used only to distinguish DRAFT (never launched) from PAUSED (launched, then disabled) in the derived status property — has no effect on discount eligibility.', null=True, verbose_name='First Activated At'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Soft-delete flag. Archived campaigns are excluded from Campaign.active() and hidden from normal admin lists, but the row (and its redemption history) is never hard-deleted — use archive() rather than .delete().', verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='Terminal state — a cancelled campaign is permanently done regardless of is_enabled/schedule/approval, and cannot be re-enabled. Use cancel() rather than setting this directly, since is_enabled=True + is_cancelled=True is rejected by clean().', verbose_name='Cancelled'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejected_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Rejected At'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Rejection Reason'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='submitted_for_approval_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Submitted At'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Last admin/dealer to save this campaign. Set by callers, not inferred automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='campaign_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Campaign UUID'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Manual on/off switch, independent of the start_at/end_at window and of approval_status. A disabled campaign never appears in .active(), even mid-window and even if approved.', verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Optional cap on the discount actually applied. Mainly useful for percentage campaigns, e.g. '30% off, up to ৳500'. Leave blank for no cap — 0 is intentionally rejected (that would zero out every discount, which is never what someone filling in this field actually means).", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Max Discount Amount'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='priority',
            field=models.IntegerField(default=0, help_text='When multiple campaigns are applicable to the same product and are NOT stackable with each other, the highest-priority one wins. Ties broken by largest discount_value.', verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='times_used',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Running redemption count. Only ever modified by Campaign.register_redemption().', verbose_name='Times Used'),
        ),
        migrations.AlterField(
            model_name='campaignredemption',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='ponno.campaign'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_enabled', 'is_cancelled', 'is_archived', 'start_at', 'end_at'], name='campaigns_is_enab_1520f5_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['approval_status'], name='campaigns_approva_cab1c7_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaign',
            constraint=models.CheckConstraint(check=models.Q(('is_cancelled', True), ('is_enabled', True), _negated=True), name='campaign_cancelled_not_enabled'),
        ),
    ]
