# Generated by Django 4.2.16 on 2026-08-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0022_remove_campaign_campaigns_campaig_c7c801_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_connect_5ed1f3_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='connected_service',
        ),
    ]
