# Generated by Django 4.2.16 on 2026-03-25 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encryption_key', models.CharField(blank=True, help_text='User-specific Fernet encryption key (auto-generated, hex-encoded)', max_length=64, null=True)),
                ('public_key', models.TextField(blank=True, help_text="User's public key for E2E encryption (PEM or OpenSSH format)", null=True)),
                ('private_key_encrypted', models.TextField(blank=True, help_text="User's private key encrypted with user's password-derived key", null=True)),
                ('jwt_private_key_encrypted', models.TextField(blank=True, help_text='Encrypted RSA private key for JWT signing (PEM format)', null=True)),
                ('jwt_public_key', models.TextField(blank=True, help_text='RSA public key for JWT verification (PEM format)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user for these keys', on_delete=django.db.models.deletion.CASCADE, related_name='keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Key',
                'verbose_name_plural': 'User Keys',
                'db_table': 'user_keys',
            },
        ),
        migrations.CreateModel(
            name='ConnectedService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_url', models.URLField(max_length=500)),
                ('service_type', models.CharField(choices=[('education', 'Education'), ('product', 'Product'), ('news', 'News'), ('location', 'location'), ('api', 'API Endpoint'), ('person', 'Person'), ('business', 'Business')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=20)),
                ('is_connected', models.BooleanField(default=False)),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('auth_token', models.TextField(blank=True, null=True)),
                ('last_fetched_data', models.JSONField(blank=True, null=True)),
                ('last_fetch_time', models.DateTimeField(blank=True, null=True)),
                ('fetch_status', models.CharField(default='pending', max_length=50)),
                ('fetch_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connected_services_profile', to='customer.profileinfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_services_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRecovery',
            fields=[
                ('recovery_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Verified email (if identity is phone or secondary email)', max_length=150, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, help_text='E.164 phone number (if identity is email or secondary phone)', max_length=20, null=True)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('phone_verified_at', models.DateTimeField(blank=True, null=True)),
                ('contact_used', models.CharField(blank=True, help_text='Email or phone number used for this recovery attempt', max_length=150)),
                ('method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], db_index=True, help_text='Recovery method used: email or phone', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of verification attempts')),
                ('max_attempts', models.PositiveSmallIntegerField(default=3, help_text='Maximum allowed verification attempts')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='Token/OTP expiration time')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(help_text='User requesting account recovery', on_delete=django.db.models.deletion.CASCADE, related_name='recovery_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recovery',
                'verbose_name_plural': 'Recovery Tables',
                'db_table': 'user_recovery_table',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='user_recove_user_id_fcc779_idx'), models.Index(fields=['method', 'contact_used'], name='user_recove_method_fdf567_idx'), models.Index(fields=['expires_at'], name='user_recove_expires_de8ef0_idx')],
            },
        ),
    ]
