# Generated by Django 4.2.16 on 2026-06-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamind', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedservice',
            name='extracted_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='extracted_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='extracted_videos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='og_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='og_site_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='og_thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='og_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='connectedservice',
            name='og_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='connectedservice',
            name='fetch_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='connectedservice',
            name='service_type',
            field=models.CharField(choices=[('education', 'Education'), ('product', 'Product'), ('news', 'News'), ('location', 'Location'), ('api', 'API Endpoint'), ('person', 'Person'), ('business', 'Business')], default='other', max_length=50),
        ),
    ]
