# Generated by Django 4.2.16 on 2026-07-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamind', '0004_alter_connectedservice_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectedservice',
            name='service_type',
            field=models.CharField(choices=[('education', 'Education'), ('product', 'Product'), ('brand', 'Brand'), ('category', 'Category'), ('subcategory', 'SubCategory'), ('news', 'News'), ('location', 'Location'), ('api', 'API Endpoint'), ('person', 'Person'), ('business', 'Business'), ('entertainment', 'Entertainment')], default='product', max_length=50),
        ),
    ]
