# Generated by Django 4.2.16 on 2026-07-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megamind', '0005_alter_connectedservice_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedservice',
            name='cached_feed_payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
