# Generated by Django 4.2.16 on 2026-07-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ponno', '0017_alter_subcategory_managed_by'),
        ('megamind', '0007_discoveryvisitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='discoveryvisitlog',
            name='product',
            field=models.ForeignKey(blank=True, editable=False, help_text='Product viewed at this visit, if this row logs a product detail hit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='megamind_discovery_visits', related_query_name='megamind_discovery_visit', to='ponno.product'),
        ),
        migrations.AddIndex(
            model_name='discoveryvisitlog',
            index=models.Index(fields=['product', 'visited_at'], name='megamind_vi_product_8381d9_idx'),
        ),
    ]
