# Generated by Django 4.2.16 on 2026-07-09 23:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('notif_type', models.CharField(choices=[('follower', 'New Follower'), ('view', 'Profile View'), ('order', 'Order'), ('wishlist', 'Wishlist'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('target_url', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this notification, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Recipient of this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WelcomeNotification',
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_d569bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notifications',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_26141b_idx'),
        ),
    ]
