# Generated by Django 4.2.16 on 2026-07-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_notifications_delete_welcomenotification_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notifications',
        ),
    ]
