# Generated by Django 4.2.16 on 2026-07-14 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0003_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique identifier for external API references', unique=True, verbose_name='UUID')),
                ('notification_type', models.CharField(choices=[('follow', 'New Follower'), ('message', 'New Message'), ('comment', 'New Comment'), ('mention', 'Mention'), ('order', 'Order Update'), ('system', 'System')], db_index=True, default='system', help_text='Category of notification', max_length=20, verbose_name='Notification Type')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', help_text='Notification priority level', max_length=10, verbose_name='Priority')),
                ('title', models.CharField(help_text='Short notification headline', max_length=150, verbose_name='Title')),
                ('message', models.TextField(blank=True, help_text='Full notification body text', max_length=500, null=True, verbose_name='Message')),
                ('action_url', models.CharField(blank=True, help_text='Relative or absolute URL to navigate to on click', max_length=255, null=True, verbose_name='Action URL')),
                ('icon', models.CharField(blank=True, help_text='Icon name/key for frontend display', max_length=50, null=True, verbose_name='Icon')),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the recipient has read this notification', verbose_name='Read')),
                ('read_at', models.DateTimeField(blank=True, help_text='Timestamp when notification was marked read', null=True, verbose_name='Read At')),
                ('send_email', models.BooleanField(default=False, help_text='Whether this notification should also be emailed', verbose_name='Send Email')),
                ('is_email_sent', models.BooleanField(default=False, help_text='Whether an email copy of this notification was sent', verbose_name='Email Sent')),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='Timestamp when the email was sent', null=True, verbose_name='Email Sent At')),
                ('email_error', models.TextField(blank=True, help_text='Error message if email delivery failed', null=True, verbose_name='Email Error')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry — notification can be hidden/pruned after this time', null=True, verbose_name='Expires At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the notification was created', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last time this notification record was updated', verbose_name='Updated At')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Soft delete timestamp', null=True, verbose_name='Deleted At')),
                ('deletion_reason', models.CharField(blank=True, help_text='Why this notification was removed', max_length=255, null=True, verbose_name='Deletion Reason')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Generic small payload for frontend use (e.g. related object IDs)', verbose_name='Data')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification metadata in JSON format', verbose_name='Metadata')),
                ('actor', models.ForeignKey(blank=True, help_text='User who triggered this notification, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_sent', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who deleted this notification, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_notifications', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['uuid'], name='notificatio_uuid_a14d7d_idx'), models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_201701_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_04e032_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f8d066_idx'), models.Index(fields=['priority'], name='notificatio_priorit_86bdfc_idx'), models.Index(fields=['created_at'], name='notificatio_created_db7ad3_idx'), models.Index(fields=['deleted_at'], name='notificatio_deleted_d16a03_idx'), models.Index(fields=['expires_at'], name='notificatio_expires_6c5b53_idx')],
            },
        ),
    ]
