# Generated by Django 4.2.16 on 2026-07-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='image',
            field=models.URLField(blank=True, help_text='Image shown alongside this notification (actor avatar, product thumbnail, etc.)', max_length=500, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='notification',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique, stable permalink slug for this notification', max_length=64, unique=True, verbose_name='Slug'),
        ),
    ]
