# Generated by Django 4.2.16 on 2026-07-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_notification_image_notification_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.CharField(blank=True, help_text='Image shown alongside this notification (actor avatar, product thumbnail, etc.)', max_length=500, null=True, verbose_name='Image'),
        ),
    ]
